name: data_hospitalization.json update

on:
  schedule:
    # Run every 8 hours
    - cron: 0 */8 * * *
  workflow_dispatch: {}

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the main repo
    - name: Checkout Main repo
      uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.data_daily_update }}
        path: site

    # Checkout data scraper repo
    - name: Checkout Data Scraper
      uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.data_daily_update }}
        repository: sfbrigade/data-covid19-sfbayarea
        path: scraper

    # The scraper uses Python 3.7+, so make sure we've got the latest 3.x
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Cache Python Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        # NOTE: we can hash these requirements files together, but keeping them
        # separate allows us to load a partial cache if only the dev
        # requirements have changed.
        key: ${{ runner.os }}-pip-${{ hashFiles('scraper/requirements.txt') }}-${{ hashFiles('scraper/requirements-dev.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ hashFiles('scraper/requirements.txt') }}-
          ${{ runner.os }}-pip-

    # Install dependencies
    # - The commit that was checked out will be available as $SCRAPER_COMMIT.
    - name: Install libxml2-dev libxslt-dev
      run: sudo apt-get install libxml2-dev libxslt-dev

    - name: Install Data Scraper & Dependencies
      run: |
        cd ${GITHUB_WORKSPACE}/scraper
        python -m pip install --upgrade pip
        pip install -r requirements.txt;

        # Keep track of the version used so we can use it in commit messages
        echo "SCRAPER_COMMIT='$(git rev-parse HEAD)'" >> $GITHUB_ENV

    - name: Scrape Data
      run: |
        echo "SCRAPER_TIME='$(date)'" >> $GITHUB_ENV
        cd ${GITHUB_WORKSPACE}/scraper
        python scraper_hospital_data.py > ${GITHUB_WORKSPACE}/site/data/data_hospitalization.json

    - name: Create PR if New Data
      uses: peter-evans/create-pull-request@v3
      with:
        path: site
        # If this branch already exists, it will be replaced with a commit
        # based on the changes from this job. If there's already a PR for it,
        # the PR will be updated. The end result is that each run of this job
        # supersedes or replaces any previous runs that haven't been reviewed
        # and merged yet.
        branch: auto-update-data-hospitalization
        title: 'GitHub action: hospitalization data update'
        body: |
          Created using commit [${{env.SCRAPER_COMMIT}}](https://github.com/sfbrigade/data-covid19-sfbayarea/commit/${{env.SCRAPER_COMMIT}})
          from sfbrigade/data-covid19-sfbayarea.

          Scraped at: ${{ env.SCRAPER_TIME }}
        commit-message: |
          GitHubAction: hospitalization data update

          Created with commit ${{env.SCRAPER_COMMIT}} from sfbrigade/data-covid19-sfbayarea
          https://github.com/sfbrigade/data-covid19-sfbayarea/commit/${{env.SCRAPER_COMMIT}}
        reviewers: kengoy
